/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC4800 SSC EtherCAT Application
*              for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2025, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "mtb_xmc_ecat.h"
#include "XMC_ESCObjects.h"
#include "ecatappl.h"
#include "applInterface.h"

void process_app(TOBJ7000 *OUT_GENERIC, TOBJ6000 *IN_GENERIC);
void SYNC0IRQHandler(void);
void SYNC1IRQHandler(void);

#define MAP2LEVEL(x) ((x==0)?XMC_GPIO_OUTPUT_LEVEL_HIGH:XMC_GPIO_OUTPUT_LEVEL_LOW)

#define PWM_CCU8_SYM_DUTY_MAX       (10000U)
#define PWM_CCU8_DUTY_FULL_SCALE    (10000U)



/*Sets the duty cycle (uint32_t) for CCU8_CC8 slice. */
bool PWM_CCU8_SetDutyCycleSymmetric(XMC_CCU8_SLICE_COMPARE_CHANNEL_t channel,
                                    uint32_t duty_cycle)
{
    uint32_t period;
    uint32_t compare;

    /* duty cycle has to be in between 0 and 100 */
    if ((duty_cycle <= PWM_CCU8_SYM_DUTY_MAX))
    {
        period = (uint32_t) XMC_CCU8_SLICE_GetTimerPeriodMatch(ccu8_0_ch_0_HW) + 1U;

        /* Duty Cycle(symmetric) = ((PR + 1)- CR) / (PR + 1) */
        compare = ((period * (PWM_CCU8_DUTY_FULL_SCALE - duty_cycle)) / PWM_CCU8_DUTY_FULL_SCALE);

        XMC_CCU8_SLICE_SetTimerCompareMatch(ccu8_0_ch_0_HW, channel, (uint16_t) compare);
        XMC_CCU8_EnableShadowTransfer(ccu8_0_HW, (uint32_t)XMC_CCU8_SHADOW_TRANSFER_SLICE_0);

    }
    return false;
} /* end of PWM_CCU8_SetDutyCycleSymmetric() api */


void process_app(TOBJ7000* OUT_GENERIC, TOBJ6000* IN_GENERIC)
{
    /* OUTPUT PROCESSING */
    /* Check bitfield set by master OUT_GEN_Bit1..8 and set LEDs accordingly */
    XMC_GPIO_SetOutputLevel(CYBSP_LED1_PORT, CYBSP_LED1_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit1));
    XMC_GPIO_SetOutputLevel(CYBSP_LED2_PORT, CYBSP_LED2_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit2));
    XMC_GPIO_SetOutputLevel(CYBSP_LED3_PORT, CYBSP_LED3_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit3));
    XMC_GPIO_SetOutputLevel(CYBSP_LED4_PORT, CYBSP_LED4_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit4));
    XMC_GPIO_SetOutputLevel(CYBSP_LED5_PORT, CYBSP_LED5_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit5));
    XMC_GPIO_SetOutputLevel(CYBSP_LED6_PORT, CYBSP_LED6_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit6));
    XMC_GPIO_SetOutputLevel(CYBSP_LED7_PORT, CYBSP_LED7_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit7));
    XMC_GPIO_SetOutputLevel(CYBSP_LED8_PORT, CYBSP_LED8_PIN, MAP2LEVEL(OUT_GENERIC->OUT_GEN_Bit8));

    /* Check integer set by Master OUT_GEN_INT1 and set duty cycle of PWM driving LED 2 accordingly */
    PWM_CCU8_SetDutyCycleSymmetric(XMC_CCU8_SLICE_COMPARE_CHANNEL_1,
                                   6000 + ((uint32_t)4000 * (uint32_t)OUT_GENERIC->OUT_GEN_INT1) / 65535);

    /* INPUT PROCESSING */
    /*Check Button 1 and set IN_GEN_Bit1 which is sent to master accordingly*/
    if (XMC_GPIO_GetInput(CYBSP_USER_BTN1_PORT, CYBSP_USER_BTN1_PIN))
        IN_GENERIC->IN_GEN_Bit1 = 1;
    else
        IN_GENERIC->IN_GEN_Bit1 = 0;

    /*Check Button 2 and set IN_GEN_Bit2 which is sent to master accordingly*/
    if (XMC_GPIO_GetInput(CYBSP_USER_BTN2_PORT, CYBSP_USER_BTN2_PIN))
        IN_GENERIC->IN_GEN_Bit2 = 1;
    else
        IN_GENERIC->IN_GEN_Bit2 = 0;
}

/**

 * @brief SYNC0IRQHandler() - EtherCAT Interrupt Routine for SYNC0
 *
 * <b>Details of function</b><br>
 * This routine is handling the SYNC0 Interrupts and need to call the SSC Stack
 */
void ERU1_2_IRQHandler(void)
{
    SYNC0IRQHandler();  // Call the Sync0 handler
}

void SYNC0IRQHandler(void)
{
    Sync0_Isr();
}

/**

 * @brief SYNC1IRQHandler() - EtherCAT Interrupt Routine for SYNC1
 *
 * <b>Details of function</b><br>
 * This routine is handling the SYNC1 Interrupts and need to call the SSC Stack
 */
 
void ERU1_0_IRQHandler(void)
{
	SYNC1IRQHandler();  // Call the Sync1 handler
}

void SYNC1IRQHandler(void)
{
    Sync1_Isr();
}

/**

 * @brief mtb_xmc_enable_user_int() - Enabling of user specific EtherCAT Interrupt Routines
 *
 * <b>Details of function</b><br>
 * This routine is called from ECAT_APP on request of SSC stack once interrupts (sync1/sync0) need to be enabled
 */
void mtb_xmc_enable_user_int()
{
    NVIC_EnableIRQ(ECAT_ERU_SYNC0_IRQN);
    NVIC_EnableIRQ(ECAT_ERU_SYNC1_IRQN);
}

/**

 * @brief mtb_xmc_disable_user_int() - Disabling of user specific EtherCAT Interrupt Routines
 *
 * <b>Details of function</b><br>
 * This routine is called from ECAT_APP on request of SSC stack once interrupts (sync1/sync0) need to be disabled
 */
void mtb_xmc_disable_user_int()
{
    NVIC_DisableIRQ(ECAT_ERU_SYNC0_IRQN);
    NVIC_DisableIRQ(ECAT_ERU_SYNC1_IRQN);
}


const XMC_GPIO_CONFIG_t  PWM_CCU8_0_ch1_out1_config    =
{
   .mode                = XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT3,
   .output_level        = XMC_GPIO_OUTPUT_LEVEL_LOW,
   .output_strength     = XMC_GPIO_OUTPUT_STRENGTH_MEDIUM
};

int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    mtb_xmc_ecat_init();

    XMC_GPIO_Init((XMC_GPIO_PORT_t *) PORT5_BASE, 8U,
            &PWM_CCU8_0_ch1_out1_config);

    /* Placeholder for user application code. The loop below can be replaced with user application code. */
    for (;;)
    {
        MainLoop();
    }

    (void)result;
}

/* [] END OF FILE */
